package com.abc.view.AdministratorView.administratorForm;

import com.abc.view.AdministratorView.components.PanelBackground;
import com.abc.view.LoginView.components.Button;
import com.abc.view.LoginView.components.ButtonOutline;
import com.abc.view.LoginView.components.RoundedTextField;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author LahiruCW
 */
public class AdministratorForm extends javax.swing.JFrame {

    private static final String ICON_PATH = "/com/abc/view/LoginView/icon/companyLogo.png";
    ImageIcon logoIcon = new ImageIcon(getClass().getResource(ICON_PATH));
    Image logoImage = logoIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
    ImageIcon scaledLogoIcon = new ImageIcon(logoImage);

    /**
     * Creates new form AdministratorForm
     */
    public AdministratorForm() {
        initComponents();
    }

    //get text from the text fields
    public String getHallName() {
        return hallNameText.getText();
    }

    public String getHallCapacity() {
        return hallCapacityText.getText();

    }

    public JPanel getBookings() {
        return Bookings;
    }

    public JPanel getCustomers() {
        return Customers;
    }

    public Button getAddButton() {
        return addButton;
    }

    public JPanel getAddHalls() {
        return addHalls;
    }

    public JLabel getAdministrator() {
        return administrator;
    }

    public JLabel getAvailableHalls() {
        return availableHalls;
    }

    public JLabel getAvailableVariable() {
        return availableVariable;
    }

    public JLabel getBookingsTopic() {
        return bookingsTopic;
    }

    public ButtonOutline getButtonOutline1() {
        return buttonOutline1;
    }

    public ButtonOutline getButtonOutline2() {
        return addHallsBtn;
    }

    public ButtonOutline getButtonOutline3() {
        return editDeleteBtn;
    }

    public ButtonOutline getButtonOutline4() {
        return customerBtn;
    }

    public ButtonOutline getButtonOutline5() {
        return bookingsBtn;
    }

    public JLabel getCompanyIcon() {
        return companyIcon;
    }

    public JPanel getEditDelete() {
        return editDelete;
    }

    public JLabel getHallsTopic() {
        return hallsTopic;
    }

    public JLabel getHallsTopicAdd() {
        return hallsTopicAdd;
    }

    public JLabel getjLabel2() {
        return hallNameLabel;
    }

    public JLabel getjLabel3() {
        return hallCapacityLabel;
    }

    /*    @Override
    public MenuBar getMenuBar() {
    return menuBar;
    }*/
    public PanelBackground getPanelBackground2() {
        return panelBackground2;
    }

    public JLayeredPane getPanelCover() {
        return panelCover;
    }

    public JPanel getRightSideCover() {
        return rightSideCover;
    }

    public RoundedTextField getRoundedTextField1() {
        return hallNameText;
    }

    public RoundedTextField getRoundedTextField2() {
        return hallCapacityText;
    }

    public PanelBackground getSummaryBookings() {
        return summaryBookings;
    }

    public PanelBackground getSummaryHalls() {
        return summaryHalls;
    }

    public JLabel getTotalBookings() {
        return totalBookings;
    }

    public JLabel getTotalHalls() {
        return totalHalls;
    }

    public JLabel getTotalHallsAdd() {
        return totalHallsAdd;
    }

    public JLabel getTotalHallsAvailable() {
        return totalHallsAvailable;
    }

    public JLabel getTotalLabel() {
        return totalLabel;
    }

    public JLabel getTotalVariable() {
        return totalVariable;
    }

    public JLabel getUserId() {
        return userId;
    }
    
    public void addHallButtonListener(ActionListener listener){
        addButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCover = new javax.swing.JLayeredPane();
        menuBar = new com.abc.view.AdministratorView.components.MenuBar();
        administrator = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();
        addHallsBtn = new com.abc.view.LoginView.components.ButtonOutline();
        editDeleteBtn = new com.abc.view.LoginView.components.ButtonOutline();
        customerBtn = new com.abc.view.LoginView.components.ButtonOutline();
        bookingsBtn = new com.abc.view.LoginView.components.ButtonOutline();
        companyIcon = new javax.swing.JLabel();
        addHallsBtn1 = new com.abc.view.LoginView.components.ButtonOutline();
        rightSideCover = new javax.swing.JPanel();
        addHalls = new javax.swing.JPanel();
        panelBackground2 = new com.abc.view.AdministratorView.components.PanelBackground();
        hallsTopicAdd = new javax.swing.JLabel();
        totalHallsAdd = new javax.swing.JLabel();
        totalHallsAvailable = new javax.swing.JLabel();
        totalVariable = new javax.swing.JLabel();
        availableVariable = new javax.swing.JLabel();
        hallNameLabel = new javax.swing.JLabel();
        hallCapacityLabel = new javax.swing.JLabel();
        hallNameText = new com.abc.view.LoginView.components.RoundedTextField();
        hallCapacityText = new com.abc.view.LoginView.components.RoundedTextField();
        addButton = new com.abc.view.LoginView.components.Button();
        buttonOutline1 = new com.abc.view.LoginView.components.ButtonOutline();
        editDelete = new javax.swing.JPanel();
        Customers = new javax.swing.JPanel();
        Bookings = new javax.swing.JPanel();
        summaryHalls = new com.abc.view.AdministratorView.components.PanelBackground();
        hallsTopic = new javax.swing.JLabel();
        totalHalls = new javax.swing.JLabel();
        availableHalls = new javax.swing.JLabel();
        summaryBookings = new com.abc.view.AdministratorView.components.PanelBackground();
        bookingsTopic = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalBookings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Allocator Administrator");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        panelCover.setBackground(new java.awt.Color(255, 255, 255));
        panelCover.setMaximumSize(new java.awt.Dimension(800, 600));
        panelCover.setMinimumSize(new java.awt.Dimension(800, 600));
        panelCover.setOpaque(true);

        menuBar.setMaximumSize(new java.awt.Dimension(300, 600));
        menuBar.setMinimumSize(new java.awt.Dimension(300, 600));
        menuBar.setPreferredSize(new java.awt.Dimension(300, 600));

        administrator.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        administrator.setForeground(new java.awt.Color(255, 255, 255));
        administrator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administrator.setText("Administrator");

        userId.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        userId.setForeground(new java.awt.Color(255, 255, 255));
        userId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userId.setText("UserID");

        addHallsBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHallsBtn.setText("Halls");
        addHallsBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        editDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        editDeleteBtn.setText("Edit and Delete Halls");
        editDeleteBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        editDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeleteBtnActionPerformed(evt);
            }
        });

        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setText("Customers");
        customerBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        bookingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookingsBtn.setText("Bookings");
        bookingsBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        companyIcon.setIcon(scaledLogoIcon);
        companyIcon.setAutoscrolls(true);
        companyIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        addHallsBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addHallsBtn1.setText("Add Halls");
        addHallsBtn1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addHallsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(bookingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addHallsBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editDeleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(administrator, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(companyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(companyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administrator)
                .addGap(27, 27, 27)
                .addComponent(addHallsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addHallsBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightSideCover.setBackground(new java.awt.Color(255, 255, 255));
        rightSideCover.setOpaque(false);
        rightSideCover.setLayout(new java.awt.CardLayout());

        addHalls.setBackground(new java.awt.Color(255, 255, 255));

        panelBackground2.setPreferredSize(new java.awt.Dimension(179, 134));

        hallsTopicAdd.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        hallsTopicAdd.setForeground(new java.awt.Color(255, 255, 255));
        hallsTopicAdd.setText("Halls");

        totalHallsAdd.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        totalHallsAdd.setForeground(new java.awt.Color(255, 255, 255));
        totalHallsAdd.setText("Total Halls");

        totalHallsAvailable.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        totalHallsAvailable.setForeground(new java.awt.Color(255, 255, 255));
        totalHallsAvailable.setText("Available");

        totalVariable.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        totalVariable.setForeground(new java.awt.Color(255, 255, 255));
        totalVariable.setText("10");

        availableVariable.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        availableVariable.setForeground(new java.awt.Color(255, 255, 255));
        availableVariable.setText("5");

        javax.swing.GroupLayout panelBackground2Layout = new javax.swing.GroupLayout(panelBackground2);
        panelBackground2.setLayout(panelBackground2Layout);
        panelBackground2Layout.setHorizontalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackground2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackground2Layout.createSequentialGroup()
                        .addComponent(hallsTopicAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBackground2Layout.createSequentialGroup()
                        .addGroup(panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackground2Layout.createSequentialGroup()
                                .addComponent(totalHallsAvailable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(availableVariable))
                            .addGroup(panelBackground2Layout.createSequentialGroup()
                                .addComponent(totalHallsAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                .addComponent(totalVariable)))
                        .addGap(48, 48, 48))))
        );
        panelBackground2Layout.setVerticalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackground2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(hallsTopicAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHallsAdd)
                    .addComponent(totalVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHallsAvailable)
                    .addComponent(availableVariable))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        hallNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hallNameLabel.setText("Hall Name");

        hallCapacityLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hallCapacityLabel.setText("Capacity");

        hallNameText.setHint("Hall name");

        hallCapacityText.setHint("Hall capacity");

        addButton.setBackground(new java.awt.Color(7, 164, 121));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        buttonOutline1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/AdministratorView/icon/undo.png"))); // NOI18N

        javax.swing.GroupLayout addHallsLayout = new javax.swing.GroupLayout(addHalls);
        addHalls.setLayout(addHallsLayout);
        addHallsLayout.setHorizontalGroup(
            addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addHallsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOutline1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addHallsLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(panelBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addHallsLayout.createSequentialGroup()
                .addGroup(addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addHallsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addHallsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hallNameLabel)
                            .addComponent(hallCapacityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hallNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hallCapacityText, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        addHallsLayout.setVerticalGroup(
            addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addHallsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(buttonOutline1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hallNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallCapacityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hallCapacityLabel))
                .addGap(27, 27, 27)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        rightSideCover.add(addHalls, "card2");

        editDelete.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout editDeleteLayout = new javax.swing.GroupLayout(editDelete);
        editDelete.setLayout(editDeleteLayout);
        editDeleteLayout.setHorizontalGroup(
            editDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        editDeleteLayout.setVerticalGroup(
            editDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        rightSideCover.add(editDelete, "card3");

        Customers.setOpaque(false);

        javax.swing.GroupLayout CustomersLayout = new javax.swing.GroupLayout(Customers);
        Customers.setLayout(CustomersLayout);
        CustomersLayout.setHorizontalGroup(
            CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        CustomersLayout.setVerticalGroup(
            CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        rightSideCover.add(Customers, "card4");

        Bookings.setOpaque(false);

        hallsTopic.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hallsTopic.setForeground(new java.awt.Color(255, 255, 255));
        hallsTopic.setText("Halls");

        totalHalls.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalHalls.setForeground(new java.awt.Color(255, 255, 255));
        totalHalls.setText("Total =");

        availableHalls.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        availableHalls.setForeground(new java.awt.Color(255, 255, 255));
        availableHalls.setText("Available = ");

        javax.swing.GroupLayout summaryHallsLayout = new javax.swing.GroupLayout(summaryHalls);
        summaryHalls.setLayout(summaryHallsLayout);
        summaryHallsLayout.setHorizontalGroup(
            summaryHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryHallsLayout.createSequentialGroup()
                .addGroup(summaryHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryHallsLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(hallsTopic))
                    .addGroup(summaryHallsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(summaryHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availableHalls)
                            .addComponent(totalHalls))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        summaryHallsLayout.setVerticalGroup(
            summaryHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryHallsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(hallsTopic)
                .addGap(19, 19, 19)
                .addComponent(totalHalls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(availableHalls)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bookingsTopic.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bookingsTopic.setForeground(new java.awt.Color(255, 255, 255));
        bookingsTopic.setText("Bookings");

        totalLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("Total");

        totalBookings.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalBookings.setForeground(new java.awt.Color(255, 255, 255));
        totalBookings.setText("10");

        javax.swing.GroupLayout summaryBookingsLayout = new javax.swing.GroupLayout(summaryBookings);
        summaryBookings.setLayout(summaryBookingsLayout);
        summaryBookingsLayout.setHorizontalGroup(
            summaryBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryBookingsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(totalBookings)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryBookingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookingsTopic)
                .addGap(58, 58, 58))
        );
        summaryBookingsLayout.setVerticalGroup(
            summaryBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryBookingsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bookingsTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(summaryBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalBookings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BookingsLayout = new javax.swing.GroupLayout(Bookings);
        Bookings.setLayout(BookingsLayout);
        BookingsLayout.setHorizontalGroup(
            BookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(summaryHalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(summaryBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        BookingsLayout.setVerticalGroup(
            BookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(summaryHalls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaryBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        rightSideCover.add(Bookings, "card5");

        panelCover.setLayer(menuBar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCover.setLayer(rightSideCover, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelCoverLayout = new javax.swing.GroupLayout(panelCover);
        panelCover.setLayout(panelCoverLayout);
        panelCoverLayout.setHorizontalGroup(
            panelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoverLayout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightSideCover, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCoverLayout.setVerticalGroup(
            panelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSideCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdministratorForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bookings;
    private javax.swing.JPanel Customers;
    private com.abc.view.LoginView.components.Button addButton;
    private javax.swing.JPanel addHalls;
    private com.abc.view.LoginView.components.ButtonOutline addHallsBtn;
    private com.abc.view.LoginView.components.ButtonOutline addHallsBtn1;
    private javax.swing.JLabel administrator;
    private javax.swing.JLabel availableHalls;
    private javax.swing.JLabel availableVariable;
    private com.abc.view.LoginView.components.ButtonOutline bookingsBtn;
    private javax.swing.JLabel bookingsTopic;
    private com.abc.view.LoginView.components.ButtonOutline buttonOutline1;
    private javax.swing.JLabel companyIcon;
    private com.abc.view.LoginView.components.ButtonOutline customerBtn;
    private javax.swing.JPanel editDelete;
    private com.abc.view.LoginView.components.ButtonOutline editDeleteBtn;
    private javax.swing.JLabel hallCapacityLabel;
    private com.abc.view.LoginView.components.RoundedTextField hallCapacityText;
    private javax.swing.JLabel hallNameLabel;
    private com.abc.view.LoginView.components.RoundedTextField hallNameText;
    private javax.swing.JLabel hallsTopic;
    private javax.swing.JLabel hallsTopicAdd;
    private com.abc.view.AdministratorView.components.MenuBar menuBar;
    private com.abc.view.AdministratorView.components.PanelBackground panelBackground2;
    private javax.swing.JLayeredPane panelCover;
    private javax.swing.JPanel rightSideCover;
    private com.abc.view.AdministratorView.components.PanelBackground summaryBookings;
    private com.abc.view.AdministratorView.components.PanelBackground summaryHalls;
    private javax.swing.JLabel totalBookings;
    private javax.swing.JLabel totalHalls;
    private javax.swing.JLabel totalHallsAdd;
    private javax.swing.JLabel totalHallsAvailable;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalVariable;
    private javax.swing.JLabel userId;
    // End of variables declaration//GEN-END:variables
}
