package com.abc.view.CustomerView.customerForm;

import com.abc.view.AdministratorView.components.Table;
import com.abc.view.CustomerView.components.CustomMouseAdapter;
import com.abc.view.LoginView.components.RoundedTextField;

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author LahiruCW
 */
public class CustomerForm extends javax.swing.JFrame {

    private static final String ICON_PATH = "/com/abc/view/LoginView/icon/companyLogo.png";
    ImageIcon logoIcon = new ImageIcon(getClass().getResource(ICON_PATH));
    Image logoImage = logoIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
    ImageIcon scaledLogoIcon = new ImageIcon(logoImage);

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        hallTable.fixTable(scrollPanel);
        initRepeatAnimation();
        periodSeclection.addItemListener(createCheckboxListener(yearEnd));
    }

    public final void initRepeatAnimation() {
        monday.addMouseListener(new CustomMouseAdapter(monday));
        tuesday.addMouseListener(new CustomMouseAdapter(tuesday));
        wednesday.addMouseListener(new CustomMouseAdapter(wednesday));
        thursday.addMouseListener(new CustomMouseAdapter(thursday));
        friday.addMouseListener(new CustomMouseAdapter(friday));
        saturday.addMouseListener(new CustomMouseAdapter(saturday));
        sunday.addMouseListener(new CustomMouseAdapter(sunday));
    }

    public Table getHallTable() {
        return hallTable;
    }

    public JLabel getUserId() {
        return userId;
    }

    public String getDateEnd() {
        return dateEnd.getText();
    }

    public String getDateStart() {
        return dateStart.getText();
    }

    public String getMonthEnd() {
        return monthEnd.getText();
    }

    public String getMonthStart() {
        return monthStart.getText();
    }

    public String getYearEnd() {
        return yearEnd.getText();
    }

    public String getYearStart() {
        return yearStart.getText();
    }
    
    //create checkbox listener
    public ItemListener createCheckboxListener(RoundedTextField textField) {
        return (ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                textField.setEditable(false);
            } else {
                textField.setEditable(true);
            }
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new com.abc.view.AdministratorView.components.MenuBar();
        companyIcon = new javax.swing.JLabel();
        bookHallbtn = new com.abc.view.LoginView.components.ButtonOutline();
        userId = new javax.swing.JLabel();
        generalUser = new javax.swing.JLabel();
        cancelBookingbtn = new com.abc.view.LoginView.components.ButtonOutline();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        dateStart = new com.abc.view.LoginView.components.RoundedTextField();
        yearStart = new com.abc.view.LoginView.components.RoundedTextField();
        monthStart = new com.abc.view.LoginView.components.RoundedTextField();
        tuesday = new javax.swing.JLabel();
        monday = new javax.swing.JLabel();
        wednesday = new javax.swing.JLabel();
        friday = new javax.swing.JLabel();
        thursday = new javax.swing.JLabel();
        sunday = new javax.swing.JLabel();
        saturday = new javax.swing.JLabel();
        button2 = new com.abc.view.LoginView.components.Button();
        title = new javax.swing.JLabel();
        buttonOutline1 = new com.abc.view.LoginView.components.ButtonOutline();
        repeatOn = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        hallTable = new com.abc.view.AdministratorView.components.Table();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yearEnd = new com.abc.view.LoginView.components.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();
        monthEnd = new com.abc.view.LoginView.components.RoundedTextField();
        jLabel4 = new javax.swing.JLabel();
        dateEnd = new com.abc.view.LoginView.components.RoundedTextField();
        periodSeclection = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Allocator Customer");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        menuBar.setMaximumSize(new java.awt.Dimension(300, 600));
        menuBar.setMinimumSize(new java.awt.Dimension(300, 600));
        menuBar.setPreferredSize(new java.awt.Dimension(300, 600));

        companyIcon.setIcon(scaledLogoIcon);
        companyIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        bookHallbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookHallbtn.setText("Book Halls");
        bookHallbtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        userId.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        userId.setForeground(new java.awt.Color(255, 255, 255));
        userId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userId.setText("UserID");

        generalUser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        generalUser.setForeground(new java.awt.Color(255, 255, 255));
        generalUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalUser.setText("General User");

        cancelBookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBookingbtn.setText("Cancel Bookings");
        cancelBookingbtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generalUser, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addGroup(menuBarLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cancelBookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(bookHallbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(companyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(companyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalUser)
                .addGap(52, 52, 52)
                .addComponent(bookHallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        dateStart.setHint("date");
        jLayeredPane1.add(dateStart);
        dateStart.setBounds(250, 330, 70, 30);

        yearStart.setHint("year");
        jLayeredPane1.add(yearStart);
        yearStart.setBounds(30, 330, 70, 30);

        monthStart.setHint("month");
        jLayeredPane1.add(monthStart);
        monthStart.setBounds(140, 330, 70, 30);

        tuesday.setBackground(new java.awt.Color(244, 242, 242));
        tuesday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tuesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuesday.setText("T");
        tuesday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tuesday.setOpaque(true);
        jLayeredPane1.add(tuesday);
        tuesday.setBounds(70, 480, 28, 28);

        monday.setBackground(new java.awt.Color(244, 242, 242));
        monday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        monday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monday.setText("M");
        monday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monday.setOpaque(true);
        jLayeredPane1.add(monday);
        monday.setBounds(30, 480, 28, 28);

        wednesday.setBackground(new java.awt.Color(244, 242, 242));
        wednesday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        wednesday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wednesday.setText("W");
        wednesday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wednesday.setOpaque(true);
        jLayeredPane1.add(wednesday);
        wednesday.setBounds(110, 480, 28, 28);

        friday.setBackground(new java.awt.Color(244, 242, 242));
        friday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        friday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friday.setText("F");
        friday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friday.setOpaque(true);
        jLayeredPane1.add(friday);
        friday.setBounds(190, 480, 28, 28);

        thursday.setBackground(new java.awt.Color(244, 242, 242));
        thursday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        thursday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thursday.setText("T");
        thursday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thursday.setOpaque(true);
        jLayeredPane1.add(thursday);
        thursday.setBounds(150, 480, 28, 28);

        sunday.setBackground(new java.awt.Color(244, 242, 242));
        sunday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sunday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sunday.setText("S");
        sunday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sunday.setOpaque(true);
        jLayeredPane1.add(sunday);
        sunday.setBounds(270, 480, 28, 28);

        saturday.setBackground(new java.awt.Color(244, 242, 242));
        saturday.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        saturday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saturday.setText("S");
        saturday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saturday.setOpaque(true);
        jLayeredPane1.add(saturday);
        saturday.setBounds(230, 480, 28, 28);

        button2.setBackground(new java.awt.Color(7, 164, 121));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Book");
        button2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLayeredPane1.add(button2);
        button2.setBounds(330, 530, 130, 26);

        title.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        title.setText("Customer Booking Section");
        jLayeredPane1.add(title);
        title.setBounds(170, 40, 190, 19);

        buttonOutline1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/AdministratorView/icon/undo.png"))); // NOI18N
        jLayeredPane1.add(buttonOutline1);
        buttonOutline1.setBounds(20, 30, 24, 34);

        repeatOn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        repeatOn.setText("Repeat on");
        jLayeredPane1.add(repeatOn);
        repeatOn.setBounds(320, 480, 70, 30);

        scrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanel.setBorder(null);
        scrollPanel.setOpaque(true);

        hallTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall ID", "Hall Name", "Capacity", "Available Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(hallTable);
        if (hallTable.getColumnModel().getColumnCount() > 0) {
            hallTable.getColumnModel().getColumn(0).setResizable(false);
            hallTable.getColumnModel().getColumn(1).setResizable(false);
            hallTable.getColumnModel().getColumn(2).setResizable(false);
            hallTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLayeredPane1.add(scrollPanel);
        scrollPanel.setBounds(40, 110, 420, 170);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("/");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(220, 330, 20, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(110, 330, 20, 30);

        yearEnd.setEditable(false);
        yearEnd.setHint("year");
        jLayeredPane1.add(yearEnd);
        yearEnd.setBounds(30, 410, 70, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("/");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(110, 410, 20, 30);

        monthEnd.setEditable(false);
        monthEnd.setHint("month");
        jLayeredPane1.add(monthEnd);
        monthEnd.setBounds(140, 410, 70, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("/");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(220, 410, 20, 30);

        dateEnd.setEditable(false);
        dateEnd.setHint("date");
        jLayeredPane1.add(dateEnd);
        dateEnd.setBounds(250, 410, 70, 30);

        periodSeclection.setBackground(new java.awt.Color(255, 255, 255));
        periodSeclection.setText("Period");
        periodSeclection.setBorder(null);
        periodSeclection.setOpaque(true);
        jLayeredPane1.add(periodSeclection);
        periodSeclection.setBounds(390, 420, 59, 20);

        jLabel5.setText("Start Date");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(30, 300, 60, 16);

        jLabel6.setText("End Date");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(30, 380, 60, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.abc.view.LoginView.components.ButtonOutline bookHallbtn;
    private com.abc.view.LoginView.components.Button button2;
    private com.abc.view.LoginView.components.ButtonOutline buttonOutline1;
    private com.abc.view.LoginView.components.ButtonOutline cancelBookingbtn;
    private javax.swing.JLabel companyIcon;
    private com.abc.view.LoginView.components.RoundedTextField dateEnd;
    private com.abc.view.LoginView.components.RoundedTextField dateStart;
    private javax.swing.JLabel friday;
    private javax.swing.JLabel generalUser;
    private com.abc.view.AdministratorView.components.Table hallTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private com.abc.view.AdministratorView.components.MenuBar menuBar;
    private javax.swing.JLabel monday;
    private com.abc.view.LoginView.components.RoundedTextField monthEnd;
    private com.abc.view.LoginView.components.RoundedTextField monthStart;
    private javax.swing.JCheckBox periodSeclection;
    private javax.swing.JLabel repeatOn;
    private javax.swing.JLabel saturday;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel sunday;
    private javax.swing.JLabel thursday;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tuesday;
    private javax.swing.JLabel userId;
    private javax.swing.JLabel wednesday;
    private com.abc.view.LoginView.components.RoundedTextField yearEnd;
    private com.abc.view.LoginView.components.RoundedTextField yearStart;
    // End of variables declaration//GEN-END:variables
}
