package com.abc.view.LoginView.loginForm;

import com.abc.view.LoginView.components.Button;
import com.abc.view.LoginView.components.LoginAndRegister;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author LahiruCW
 */
public class LoginForm extends javax.swing.JFrame {
    
    private MigLayout layout;

    /**
     * Creates new form loginForm
     */
    public LoginForm() {
        initComponents();
        init();
    }

    public void init(){
        layout = new MigLayout("fill, insets 0");
        background.setLayout(layout);   
    }

    public LoginAndRegister getLoginAndRegister1() {
        return loginAndRegister1;
    }
    
    //return sign up button
    public Button getSignUpButton(){
        
        return loginAndRegister1.getSignUp();
    }
    
    //return sign in button
    public Button getSignInButton(){
        
        return loginAndRegister1.getSignIn();
    }
    
    public JPanel getSignUpPanel(){
        return loginAndRegister1.getRegisterPanel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLayeredPane();
        loginAndRegister1 = new com.abc.view.LoginView.components.LoginAndRegister();
        gradientPanel2 = new com.abc.view.LoginView.components.GradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Allocator Login and Sign Up");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setOpaque(true);

        gradientPanel2.setMaximumSize(new java.awt.Dimension(300, 600));
        gradientPanel2.setMinimumSize(new java.awt.Dimension(300, 600));
        gradientPanel2.setPreferredSize(new java.awt.Dimension(300, 600));

        background.setLayer(loginAndRegister1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(gradientPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(gradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAndRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginAndRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane background;
    private com.abc.view.LoginView.components.GradientPanel gradientPanel2;
    private com.abc.view.LoginView.components.LoginAndRegister loginAndRegister1;
    // End of variables declaration//GEN-END:variables
}
