package com.abc.view.LoginView.components;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author LahiruCW
 */
public class GradientPanel extends javax.swing.JPanel {
    
    private MigLayout layout;
    private JLabel titleLabel;
    private JLabel descriptionOne;
    private JLabel descriptionTwo;
    private JLabel descriptionThree;

    /**
     * Creates new form GradientPanel
     */
    public GradientPanel() {
        initComponents();
        setOpaque(false);
        layout = new MigLayout("wrap, fill","[center]","push[]10[]10[]10[]push");
        setLayout(layout);
        init();
    }
    
    private void init(){
        titleLabel = new JLabel("Welcome Back!");
        titleLabel.setFont(new Font("sansserif",1,30));
        titleLabel.setForeground(new Color(245,245,245));
        add(titleLabel);
        
        descriptionOne = new JLabel("To keep connected with us please");
        descriptionOne.setForeground(new Color(245, 245, 245));
        add(descriptionOne);
        
        descriptionTwo = new JLabel("login with your personal info");
        descriptionTwo.setForeground(new Color(245, 245, 245));
        add(descriptionTwo);
        
        descriptionThree = new JLabel("or create an account with sign up");
        descriptionThree.setForeground(new Color(245, 245, 245));
        add(descriptionThree);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics graphics){
        Graphics2D g2 = (Graphics2D) graphics;
        GradientPaint gradient = new GradientPaint(0, 0, new Color(35,166,97), 0,getHeight(),new Color(22,166,66));
        g2.setPaint(gradient);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(graphics);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
